jualo_web/config/routes.rb
Rails.application.routes.draw do
  resources :brands,        only: [:index, :show]
  resources :categories,    only: [:index, :show]
  resources :products,      only: [:index, :show]
  resources :products do
    collection do
      match "search" => "products/search", via: [:get, :post], as: :set_search
    end
  end
  root "static_pages#home"
  # root "products#show"
  devise_for :users
  as :user do
    get      "/signin",      to: "devise/sessions#new"
    get      "/signup",      to: "devise/registrations#new"
    delete   "/signout",     to: "devise/sessions#destroy"
    get      "/profile",     to: "devise/#method"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

jualo_web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # ransack_alias :product, :name_or_status_cont
end

jualo_web/app/models/brand.rb
class Brand < ApplicationRecord
  has_many :brand_details
  has_many :categories, through: :brand_details
end

jualo_web/app/models/brand_detail.rb
class BrandDetail < ApplicationRecord
  belongs_to :brand
  belongs_to :category
end

jualo_web/app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  has_many :brand_details
  has_many :brands, through: :brand_details
end

jualo_web/app/models/pro_detail.rb
class ProDetail < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :pro_spec

  has_many :pro_images
end

jualo_web/app/models/pro_image.rb
class ProImage < ApplicationRecord
  belongs_to :pro_detail
end

jualo_web/app/models/pro_spec.rb
class ProSpec < ApplicationRecord
end

jualo_web/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many :pro_details
  has_many :users, through: :pro_details
end

jualo_web/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pro_details
  has_many :products,  through: :pro_details
end

jualo_web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  # before_action :search_simple_form_for

  PER_PRODUCT_OF_PAGE = 20
 
  protected
 
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  # Search with name of product
  def set_search
    @search = Product.ransack(params[:q])
    @products_search = @search.result(distinct: true)
    @products = get_product_paginate(id: @products_search)
  end

  def get_products_detail(param)
    Product.joins(:pro_details, :category)
            .select("pro_details.id", "products.name", "products.status" , "pro_details.price")
            .where(param)
  end

  def get_product_paginate(param)
    get_products_detail(param).page(params[:page]).per(PER_PRODUCT_OF_PAGE)
  end
  
end

jualo_web/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_categories, only: [:show]
  before_action :set_product, only: [:show]
  before_action :get_value_spec, only: [:show]

  def index
  end

  def show
  end
  
  private
    def set_product
      @products = get_product_paginate(category: @categories)
    end

    def set_categories
      @categories = Category.joins(:brands, :brand_details)
            .select("categories.id")
            .where("brands.id": params[:id])
    end
    
    def get_value_spec
      @types         = column_name_distinct(:name)
      @transmissions = column_name_distinct(:transmission)
      @colors        = column_name_distinct(:color)
      @years         = column_name_distinct(:year)
      @fuels         = column_name_distinct(:fuel)
    end

    def column_name_distinct(title)
      ProSpec.select(title).distinct
    end
end

jualo_web/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_product, only: [:show]
  before_action :set_category, only: [:show]

  def index
  end

  def show
  end

  private
    def set_product
      @products = get_product_paginate(category: params[:id])
    end
    
    def set_category
      @category = Category.find(params[:id])
    end
    
end

jualo_web/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @category = Category.first
    # @searchs = params[:search]
    # if @searchs.present?
    #   @name = @searchs["name"]
    #   puts "#{@name}"
    #   @product_search = Product.where("id LIKE ?", "#{@name}")
    #   puts "#{@product_search}"
    #   @products = get_product_paginate(id: @products_search)
    #   puts "#{@products}"      
    # end
  end

  def show
    @product_images = @product_detail.pro_images
  end

  private
    def set_product
      @product_detail = ProDetail.find(params[:id])
    end
    
end

jualo_web/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @categories = Category.where(parent_id: 0)

    @brands_car     = set_brand(1)
    @brands_motor   = set_brand(2)

    # 1 is id of category car
    # 2 is id of category motor
    @product_motors = get_products_detail(category: 2).limit(6)
    @product_cars   = get_products_detail(category: 1).limit(6)
  end

  def set_brand(id)
    @category = Category.find(id)
    @brands   = @category.brands.limit(5)
  end

end

jualo_web/app/helpers/application_helper.rb
module ApplicationHelper
end

jualo_web/app/helpers/brands_helper.rb
module BrandsHelper
end

jualo_web/app/helpers/categories_helper.rb
module CategoriesHelper
end

jualo_web/app/helpers/products_helper.rb
module ProductsHelper
end

jualo_web/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

jualo_web/app/views/brands/index.html.erb
<h1>Brands#index</h1>
<p>Find me in app/views/brands/index.html.erb</p>

jualo_web/app/views/brands/show.html.erb
<%= render partial: "contents/form_content",
  locals: {
    products:    @products, 
    category:    @categories,
    image_error: "https://storage.jualo.com/big_thumb/19496363/yamaha-vega-zr-2009-motor-yamaha-19496363.jpg",    
    is_category: true,
    is_brand:    true,
    is_home:     false
  }
%>

jualo_web/app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

jualo_web/app/views/categories/show.html.erb
<%= render partial: "contents/form_content",
  locals: {
    products:    @products, 
    category:    @category,
    image_error: "https://storage.jualo.com/big_thumb/19496363/yamaha-vega-zr-2009-motor-yamaha-19496363.jpg",    
    is_category: true,
    is_brand:    false,
    is_home:     false
  }
%>

jualo_web/app/views/contents/_filter.erb
<div class="category-listing__nav">
  <div class="col-12 category-listing__nav-head">
    <div class="pull-left">
      <%= content_tag(:span) do %>
      <%= link_to "Home", "/" %>
      <% end %>
      <%= content_tag(:span, class: "arrow") do %>
      &gt;
      <% end %>
      <%= link_to "#" do %>
      <%= category.name %>
      <% end %>
    </div>
    <div class="pull-right">
      search results found
      <%= content_tag(:span, products.length) %>
    </div>
  </div>
  <div class="col-12 category-listing__nav-content">
    <div class="pull-left">
      <div class="category-listing__location">
        <%= content_tag(:span, "", class: "icon icon_location") %>
        <input type="text" name="lokasi" id="lokasi" placeholder="Cari Berdasarkan Lokasi..." autocomplete="off">
        <div class="clear-location">
          <%= content_tag(:span, "", class: "icon icon_close") %>
        </div>
      </div>
      <div class="category-listing__suggestion">
        <ul class="category-listing__suggestion-list"></ul>
      </div>
    </div>
    <div class="pull-right">
      <div class="category-listing__type">
        <label>
          <%= link_to "#" do %>
          <!-- <a onclick="setCookie('applied_filter', true);" href="/motor/sparepart-motor"> -->
          <input checked="" class="milan-radio" name="tipe-produk" type="radio">
          <span> </span>
          all
          <!-- </a> -->
          <% end %>
        </label>
        <label>
          <%= link_to "#" do %>
          <!-- <a onclick="setCookie('applied_filter', true);" href="/motor/sparepart-motor/baru"> -->
          <input class="milan-radio" name="tipe-produk" type="radio">
          <span></span>
          new
          <!-- </a> -->
          <% end %>
        </label>
        <label>
          <%= link_to "#" do %>
          <!-- <a onclick="setCookie('applied_filter', true);" href="/motor/sparepart-motor/bekas"> -->
          <input class="milan-radio" name="tipe-produk" type="radio">
          <span></span>
          former
          <!-- </a> -->
          <% end %>
        </label>
      </div>
      <div class="category-listing__sort">
        <%= content_tag(:span, "", class: "icon icon_sort") %>

        <select name="sort_by" id="sort_by" class="jualo_select sort_by" onchange="$('#filter_category').submit()">
          <option value="">
            Sort by
          </option>
          <option value="date">
            The latest
          </option>
          <option value="price_low_to_high">
            Cheapest
          </option>
          <option value="price_high_to_low">
            Most expensive
          </option>
        </select>
        <%= content_tag(:span, "", class: "icon icon_dropdown") %>
      </div>
    </div>
  </div>

  <%= render "contents/suggest" %>
</div>  

jualo_web/app/views/contents/_filter_brand.html.erb
<div class="category-listing__nav">
  <div class="col-12 category-listing__nav-head">
    <div class="pull-left">
      <%= content_tag(:span) do %>
      <%= link_to "Home", "/" %>
      <% end %>
      <%= content_tag(:span, class: "arrow") do %>
      &gt;
      <% end %>
      <span>
        <a href="/motor" onclick="document.cookie='category_ids=[]'">
          Motor
        </a>
      </span>
      <span class="arrow">
        &gt;
      </span>
      <span>
        <a href="/motor/baru-dan-bekas" onclick="document.cookie='category_ids=[]'">
          Motor Baru &amp; Bekas
        </a>
      </span>
      <span class="arrow">
        &gt;
      </span>
      <span>
        <a onclick="document.cookie='category_ids=[]'" href="/semua">
          Honda
        </a>
      </span>
    </div>
    <div class="pull-right">
      Search Results Found
      <%= content_tag(:span, products.length) %>
    </div>
  </div>
  <div class="col-12 category-listing__nav-content">
    <div class="pull-left">
      <div class="category-listing__location">
        <span class="icon icon_location"></span>
        <input type="text" name="lokasi" id="lokasi" placeholder="Cari Berdasarkan Lokasi..." autocomplete="off">
        <div class="clear-location">
          <span class="icon icon_close"></span>
        </div>
      </div>
      <div class="category-listing__suggestion">
        <ul class="category-listing__suggestion-list"></ul>
      </div>
    </div>
    <div class="pull-right">
      <div class="category-listing__type">
        <label>
          <a onclick="setCookie('applied_filter', true);" href="/baru-dan-bekas/motor-honda"><input checked=""
              class="milan-radio" name="tipe-produk" type="radio">
            <span></span>
            semua
          </a></label>
        <label>
          <a onclick="setCookie('applied_filter', true);" href="/baru-dan-bekas/motor-honda/baru"><input
              class="milan-radio" name="tipe-produk" type="radio">
            <span></span>
            baru
          </a></label>
        <label>
          <a onclick="setCookie('applied_filter', true);" href="/baru-dan-bekas/motor-honda/bekas"><input
              class="milan-radio" name="tipe-produk" type="radio">
            <span></span>
            bekas
          </a></label>
      </div>
      <div class="category-listing__sort">
        <span class="icon icon_sort"></span>
        <select name="sort_by" id="sort_by" class="jualo_select sort_by" onchange="$('#filter_category').submit()">
          <option value="">Urutkan</option>
          <option value="date">Terbaru</option>
          <option value="price_low_to_high">Termurah</option>
          <option value="price_high_to_low">Termahal</option>
        </select>
        <span class="icon icon_dropdown"></span>
      </div>
    </div>
  </div>

  <%= render "contents/filter_by" %>
</div>

jualo_web/app/views/contents/_filter_by.html.erb
<div class="col-12 category-listing__nav-advanced active">
  <div class="category-listing__advanced">
    <div class="row">
      <div class="col-12">
        <div class="advanced-list">
          <div class="title">
            Type
          </div>
          <div class="milan-select-option">
            <div class="arrow down grey-small"></div>
            <%= select_tag "type", options_from_collection_for_select(@types, "id", "name") %>
          </div>
        </div>
        <div class="advanced-list">
          <div class="title">
            Tahun
          </div>
          <div class="milan-select-option">
            <div class="arrow down grey-small"></div>
            <%= select_tag "year", options_from_collection_for_select(@years, "id", "year") %>
          </div>
        </div>
        <div class="advanced-list">
          <div class="title">
            Transmission
          </div>
          <div class="milan-select-option">
            <div class="arrow down grey-small"></div>
            <%= select_tag "transmission", options_from_collection_for_select(@transmissions, "id", "transmission") %>
          </div>
        </div>
        <div class="advanced-list">
          <div class="title">
            Kilometer
          </div>
          <div class="milan-select-option">
            <div class="arrow down grey-small"></div>
            <select name="filter_kilometer" id="filter_kilometer" data-validate="true" data-required="false"
              data-field="dropdown">
              <option value="">Pilih Kilometer</option>
              <option value="0-5000">0-5000</option>
              <option value="5001-10000">5001-10000</option>
              <option value="10001-15000">10001-15000</option>
              <option value="15001-20000">15001-20000</option>
              <option value="20001-25000">20001-25000</option>
              <option value="25001-30000">25001-30000</option>
              <option value=">30000">&gt;30000</option>
            </select>
          </div>
        </div>
        <div class="advanced-list">
          <div class="title">
            Fuel
          </div>
          <div class="milan-select-option">
            <div class="arrow down grey-small"></div>
            <%= select_tag "fuel", options_from_collection_for_select(@fuels, "id", "fuel") %>
          </div>
        </div>
        <div class="advanced-list">
          <div class="title">
            Warna
          </div>
          <div class="milan-select-option">
            <div class="arrow down grey-small"></div>
            <%= select_tag "color", options_from_collection_for_select(@colors, "id", "color") %>
          </div>
        </div>
        <div class="advanced-list">
          <div class="title">
            CC
          </div>
          <div class="content">
            <input class="milan-input milan-input--right-text" data-field="textbox" data-required="false"
              data-type="string" data-validate="true" id="attributes_611" name="filter_cc" type="text" value="">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 margin-bottom">
      <div class="advanced-button-container pull-right">
        <!-- <%= button_to "Reset", name: "button", type: "button", class: "button button--white button-reset" %> -->
        <button name="button" type="button" class="button button--white button-reset">Reset</button>
        <button name="button" type="button" class="button button--orange button-result"
          onclick="$('#filter_category').submit()">Tampilkan Hasil</button>
      </div>
    </div>
  </div>
</div>

jualo_web/app/views/layouts/_header.html.erb
<header class="full-width header-fixed-top bg-header">
  <div class="container main-header">
    <div class="row">
      <div class="col-12">
        <div class="pull-left">
          <div class="main-header__logo">
            <h1 title="Jualo.com Teman Jual Belimu">
              <%= link_to root_path do %>
              <%= image_tag ("https://www.jualo.com/assets/milan_version/header-logo-white-6a883b85e00ccc9adbb5b25e7ab01687b84414e86ec94c6740e0c7501e8f38e9.png") %>
              <% end %>
            </h1>
          </div>
        </div>
        <div class="pull-right">
          <div class="main-header__location">
            <%= content_tag(:span, "", class: "icon icon_lokasi") %>
            <%= content_tag(:span, "", class: "icon-dropdown icon_dropdown-white") %>
          </div>


          <!-- <%= simple_form_for :search, url: products_path, method: "GET", 
            class: "search" do |f| %>
            <%= content_tag(:span, class: "twitter-typeahead", style: "position: relative; display: inline-block;") do %>
              <%= f.input :name,
                id:    "search_field",
                class: "js-searchbox tt-input",
                autocomplete: "off",
                placeholder: "search for ads",
                type:  "text", 
                spellcheck: "false",
                dir:   "auto",
                style: "position: relative; vertical-align: top;",
                input_html: { value: "" } 
              %>
              <%= f.submit "Search" %>
            <% end %>
          <% end %> -->
          <div class="main-header__search">

            <%= search_form_for @search, class: "search" do |f| %>      
              <%= content_tag(:span, class: "twitter-typeahead", style: "position: relative; display: inline-block;") do %>
                <%= f.search_field :name_or_status_cont,
                  id:    "search_field",
                  class: "js-searchbox tt-input",
                  autocomplete: "off",
                  placeholder: "search for ads",
                  type:  "text", 
                  spellcheck: "false",
                  dir:   "auto",
                  style: "position: relative; vertical-align: top;"
                %>

                <pre aria-hidden="true"
                  style="position: absolute; visibility: hidden; white-space: pre; font-family: ArialMT; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: capitalize;"></pre>
                <div class="tt-menu suggest-custom-menu"
                  style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;">
                  <div class="tt-dataset tt-dataset-best-pictures"></div>
                </div>
              <% end %>

              <div class="icon_w_loader_header">
                <i class="fa fa-spinner fa-spin"></i>
              </div>
              <div class="clear-search js-clear-w-input-search">
                <%= content_tag(:span, "", class: "icon icon_close_fix") %>
              </div>
              <%= f.submit class: "button icon icon_search", id: "search_button" %>
            <% end %>

          </div>
          <div class="main-header__placing-ad">
            <%= link_to "#", class: "header_new_ad initiate-post-product" do %>
            <%= content_tag(:span, "", class: "icon icon-pasang-iklan") %>
            <%= content_tag(:span, "Placing ad" ,class: "text") %>
            <% end %>
          </div>
          <div class="account-not-signin main-header__account" id="dropdown">
            <%= content_tag(:span, "",class: "icon icon_akun") %>
            <%= content_tag(:span, "",class: "icon icon_akun2") %>
            <div class="account-dropdown">
              <% if current_user.nil? %>
              <%= render "layouts/not_login" %>
              <% else %>
              <%= render "layouts/is_login" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

jualo_web/app/views/layouts/_is_login.html.erb
<div class="account-dropdown-login__user">
  <a href="#">
    <%= content_tag(:span, class: "user-photo") do %>
    <%= image_tag("https://www.jualo.com/assets/noavatar-8c11c7c8dd0aaccd941b0ca4d86be3f5d08075272faa0c2c6b0ec2bd06943830.png", 
      alt: "Noavatar", backup_img: "avatar") 
    %>
    <% end %>
    <%= content_tag(:span, current_user.username) %>
    <br>
    <span class="user-location">

    </span>
  </a>
</div>
<div class="account-dropdown-login__list">
  <%= link_to "#" do %>
  <div>My Ad</div>
  <% end %>
  <%= link_to "#" do %>
  <div>Ad Rejected</div>
  <% end %>
  <%= link_to "#" do %>
  <div>Favorite</div>
  <% end %>
</div>
<div class="account-dropdown-login__list">
  <%= link_to "#" do %>
  <div>Message</div>
  <% end %>
  <%= link_to "#" do %>
  <div>Notification</div>
  <% end %>
  <%= link_to "#" do %>
  <div>Feedback</div>
  <% end %>
</div>
<div class="account-dropdown-login__list">
  <%= link_to "#" do %>
  <div>Furse</div>
  <% end %>
</div>
<div class="account-dropdown-login__list">
  <%= link_to "#" do %>
  <div>Edit Account</div>
  <% end %>
  <%= link_to signout_path, method: :delete, class: "btn-no-alert" do %>
  <div>Logout</div>
  <% end %>
</div>

jualo_web/app/views/layouts/_not_login.html.erb
<div class="account-dropdown__welcome">Welcome to Selling!</div>
<div class="account-dropdown__login">
  <%= link_to  "LOGIN", signin_path, 
    { class: "button button--green", ref: "nofollow", 
    "data-toggle": "modal", "data-target": "#loginModal" } 
  %>
</div>
<div class="account-dropdown__login-with">or login with</div>
<div class="account-dropdown__social-media row">
  <div class="col-6 facebook">
    <a class="fbpopup button button--facebook" data-height="400" data-width="600" href="/users/auth/facebook"
      id="fbpopup1" onclick="return open_authorization_windows(this);" rel="nofollow" rp="https://www.jualo.com/"
      target="_blank">
      facebook
    </a>
  </div>
  <div class="col-6 google">
    <a class="fbpopup button button--google" data-height="500" data-width="600" href="/users/auth/google" id="fbpopup1"
      onclick="return open_authorization_windows(this);" rel="nofollow" rp="https://www.jualo.com/" target="_blank">
      google+
    </a>
  </div>
</div>
<div class="account-dropdown__line"></div>
<div class="account-dropdown__not-have">Do not have an account?</div>
<div class="account-dropdown__sign-in">
  <%= link_to  "REGISTER", signup_path, 
    { class: "button button--orange", ref: "nofollow", 
    "data-toggle": "modal", "data-target": "#signupModal" } 
  %>
</div>

jualo_web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>
    <%= yield(:title) %>
  </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "layouts/header" %>
  <!-- <%= notice %> -->
  <!-- <%= alert %> -->
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
  <% end %>
  </div>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>

</html>

jualo_web/app/views/products/_cate_select.html.erb
<div class="product-details-container-with-seller-and-more-ads">
  <div class="col-12 product-detail__head">
    <div class="product-detail__head-tree">
      <%= link_to "Home", root_path %>
      <%= content_tag(:span, class: "arrow") do %>
        &gt;
      <% end %>
      <%= link_to "#" do %>
        <%= product.product.category.name %>
      <% end %>
      <%= content_tag(:span, class: "arrow") do %>
        &gt;
      <% end %>
      <!-- <%= link_to "#" do %>
        Yamaha in Bandung City, West Java
      <% end %>
      <%= content_tag(:span, class: "arrow") do %>
        &gt;
      <% end %> -->
      <%= content_tag(:span, class: "current-cat") do %>
        <%= product.product.name %>
      <% end %>
    </div>
  </div>
</div>

jualo_web/app/views/products/_category_select.html.erb
<div class="product-details-container-with-seller-and-more-ads">
  <div class="col-12 product-detail__head">
    <div class="product-detail__head-tree">
      <%= link_to "Home", root_path %>
      <%= content_tag(:span, class: "arrow") do %>
        &gt;
      <% end %>
      <%= link_to "#" do %>
        <%= product.product.category.name %>
      <% end %>
      <%= content_tag(:span, class: "arrow") do %>
        &gt;
      <% end %>
      <%= content_tag(:span, class: "current-cat") do %>
        <%= product.product.name %>
      <% end %>
    </div>
  </div>
</div>

jualo_web/app/views/products/_list_product_image.html.erb
<div class="bxslider">
  <% product_images.each do |image| %>
  <%= image_tag(image.image, alt: "", original: image.image, title: "", backup_img: "product_thumb") %>
  <% end %>
</div>

jualo_web/app/views/products/_spec_content.html.erb
<div class="specification__list">
  <div class="row">
    <div class="col-5">
      <div class="title">
        <%= title %>
      </div>
    </div>
    <div class="col-7 pad-0">
      <%= content %>
    </div>
  </div>
</div>

jualo_web/app/views/products/index.html.erb
<%= render partial: "contents/form_content",
  locals: {
    products:    @products, 
    category:    @category,
    image_error: "https://storage.jualo.com/big_thumb/19496363/yamaha-vega-zr-2009-motor-yamaha-19496363.jpg",    
    is_category: true,
    is_brand:    false
  }
%>

jualo_web/app/views/products/show.html.erb
<section class="row full-width product-detail">
  <div class="container">
    <div class="col-12">
      <%= render partial: "category_select", locals: { product: @product_detail } %>
      <%= render partial: "content_product", locals: { product: @product_detail, product_images: @product_images } %>
    </div>
  </div>
</section>

jualo_web/app/views/static_pages/_banner.html.erb
<div class="col-6 pad-0">
  <%= link_to category_path(2) do %>
  <% image_tag("https://www.jualo.com/assets/milan_version/banners/banner-motor-v2-ad7bb763f89838de86a891a152d58e211b8d0f275ee503bfd090b69dd4b1247c.jpg", 
    class: "home-banner home-top-banners main-banner", alt: "Banner motor v2") %>
  <% end %>
</div>
<div class="col-3 pad-0">
  <%= link_to category_path(1) do %>
  <% image_tag("https://www.jualo.com/assets/milan_version/banners/banner-mobil-688571761bb48c817abe6c5e2d40d88931b78cb474814f53c5cd2ca3a86c8cf5.jpg", 
    class: "home-banner home-top-banners", alt: "Banner mobil") %>
  <% end %>
</div>
<div class="col-3 pad-0">
  <%= link_to "#" do %>
  <% image_tag("https://www.jualo.com/assets/milan_version/banners/properti-1-9dc794df172c383af1e78cc596c71629b654746716f93b577504ef7f8ab67c1c.jpg", 
      class: "home-banner", alt: "Properti 1") %>
  <% end %>
</div>
<div class="col-3 pad-0">
  <%= link_to "#" do %>
  <% image_tag("https://www.jualo.com/assets/milan_version/banners/properti-2-df52ea202aec7f7b66eade607b2e5fb0cb601c41cb3c0e690e8de45f1a455605.jpg", 
      class: "home-banner", alt: "Properti 2") %>
  <% end %>
</div>
<div class="col-3 pad-0">
  <%= link_to "#" do %>
  <% image_tag("https://www.jualo.com/assets/milan_version/banners/properti-3-0ce1ecb679ded7a04a5e94871c62d8659d9b519eb6a60403d16c99f486e554ca.jpg", 
      class: "home-banner", alt: "Properti 3") %>
  <% end %>
</div>